name: Build Windows

on:
  push:
  pull_request:

jobs:
  tests-windows:
    name: Tests
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        php:
          - '7.4'
          - '8.0'
          - '8.1'
        librdkafka:
          - '1.8.2'
    continue-on-error: ${{ matrix.php == '8.1' }}
    defaults:
      run:
        shell: bash
    env:
      PHP_VERSION: ${{ matrix.php }}
      LIBRDKAFKA_VERSION: v${{ matrix.librdkafka }}
      KAFKA_BROKERS: localhost:9092
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install librdkafka & kafka
        run: |
          nuget install librdkafka.redist -Version ${{ matrix.librdkafka }}
          choco install --no-progress wget nssm
          wget -q -O kafka_2.13-3.0.0.tgz http://ftp.fau.de/apache/kafka/3.0.0/kafka_2.13-3.0.0.tgz
          tar -xzf kafka_2.13-3.0.0.tgz
          cp -pr kafka_2.13-3.0.0 /c/kafka
          sed -i "s|broker.id=0|broker.id=111|g" /c/kafka/config/server.properties
          nssm install zookeeper /c/kafka/bin/windows/zookeeper-server-start.bat /c/kafka/config/zookeeper.properties
          nssm set zookeeper AppExit Default Exit
          nssm install kafka /c/kafka/bin/windows/kafka-server-start.bat /c/kafka/config/server.properties
          nssm set kafka AppExit Default Exit

      - name: Start Kafka
        run: |
          nssm start zookeeper
          nssm status zookeeper
          nssm start kafka
          nssm status kafka

      - name: Install PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: ffi

      - name: Get composer cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer cache directory
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-${{ matrix.php }}-composer-
      - name: Install dependencies
        run: |
          composer update --prefer-dist --prefer-stable --no-interaction

      - name: Run tests
        run: |
          export PATH=$PWD/librdkafka.redist.1.8.2/runtimes/win-x64/native:$PATH
          composer test-init
          vendor/bin/phpunit --verbose --debug;

      - name: Stop kafka
        run: |
          nssm stop kafka
          nssm stop zookeeper